control_baches/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
  # INDEX URL
  path('', views.IndexView, name='index'),
  # Auth    
  path('login/', views.LoginView.as_view(), name='login'),
  path('logout/', views.LogoutView.as_view(), name='logout'),
  path('register/', views.signup, name='register'),
#Dashboard
  path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
  path('crear-bache/', views.CrearReporteBacheView.as_view(), name='crear-bache'),
  path('detalle-bache/', views.DetalleBacheView.as_view(), name='detalle-bache'),
  path('reporte-baches/', views.ReporteBachesView.as_view(), name='reporte-baches'),
]

web/models.py
from django.db import models

# Create your models here.

web/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.views.generic import TemplateView, DetailView, View 

def IndexView(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('web:dashboard'))
    else:
        return redirect(reverse_lazy('web:login'))

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse_lazy('web:dashboard'))
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

class LoginView(auth_views.LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy('web:dashboard'))
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class LogoutView(auth_views.LogoutView):
    pass


class DashboardView(LoginRequiredMixin, TemplateView):
  template_name = 'dashboard.html'

class CrearReporteBacheView(LoginRequiredMixin, TemplateView):
  template_name = 'crear_bache.html'

class DetalleBacheView(LoginRequiredMixin, TemplateView):
  template_name = 'detalle_bache.html'

class ReporteBachesView(LoginRequiredMixin, TemplateView):
  template_name = 'reporte_baches.html'

web/templates/crear_bache.html
{% extends 'global/base.html' %} {% load static %} {% block title %} Reportar
nuevo bache {% endblock %} {% block style %}
<style></style>
{% endblock %} {% block content %}

<h1>CREAR NUEVO REPORTE DE BACHE</h1>

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <p class="card-description">Agregue los datos del bache</p>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Departamento</label>
              <div class="col-sm-9">
                <input
                  type="text"
                  class="form-control"
                  value="Quetzaltenango"
                />
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Municipio</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="Salcaja" />
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nivel de daño</label>
              <div class="col-sm-9">
                <select class="form-control">
                  <option>Regular</option>
                  <option>Moderado</option>
                  <option>Severo</option>
                  <option>No se puede transitar</option>
                </select>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label"
                >Adjuntar coordenadas</label
              >
              <div class="col-sm-9">
                <input
                  type="text"
                  class="form-control"
                  value="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title d-flex">Adjuntar foto</h4>
                <input type="file" class="dropify" />
              </div>
            </div>
          </div>
        </div>
        <button type="button" class="btn btn-success mr-2" onclick="handleSubmit()">Guardar</button>
        <a href="/" class="btn btn-danger mr-2">Cancelar</a>
      </form>
    </div>
  </div>
</div>

{% endblock %} 

{% block js %} 
<script>
    
</script>
{% endblock %}

web/templates/dashboard.html
{% extends 'global/base.html' %} {% load static %} {% block title %} Dashboard
{% endblock %} {% block style %}
<style></style>
{% endblock %} {% block content %}

<h1>DASHBOARD</h1>

<div class="row">
  <div class="col-md-4 grid-margin stretch-card">
    <div class="card">
      <div class="card-body text-center">
        <div class="text-primary mb-4">
          <i class="mdi mdi-account-multiple mdi-36px"></i>
          <p class="font-weight-medium mt-2">Usuarios activos</p>
        </div>
        <h1 class="font-weight-light">45679</h1>
        <p class="text-muted mb-0">Incremento del 20%</p>
      </div>
    </div>
  </div>
  <div class="col-md-4 grid-margin stretch-card">
    <div class="card">
      <div class="card-body text-center">
        <div class="text-danger mb-4">
          <i class="mdi mdi-chart-pie mdi-36px"></i>
          <p class="font-weight-medium mt-2">Reportes realizados el último mes</p>
        </div>
        <h1 class="font-weight-light">809</h1>
        <p class="text-muted mb-0">Ingremento del 60%</p>
      </div>
    </div>
  </div>
  <div class="col-md-4 grid-margin stretch-card">
    <div class="card">
      <div class="card-body text-center">
        <div class="text-info mb-4">
          <i class="mdi mdi-car mdi-36px"></i>
          <p class="font-weight-medium mt-2">Baches reparados el último mes</p>
        </div>
        <h1 class="font-weight-light">150</h1>
        <p class="text-muted mb-0">Incremento del 2%</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Ultimas 5 entradas</h4>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Quien reporta</th>
                <th>Coordenadas</th>
                <th>Fecha de reporte</th>
                <th>Descripción</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Juan Perez Rodiguez</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver Mapa</a
                  >
                </td>
                <td>2018-12-19 09:26:03 AM</td>
                <td>
                  Se encuentra en una calle transitada por lo que representa un
                  gran peligro para los automovies
                </td>
                <td>
                  <a href="{% url 'web:detalle-bache' %}" target="_blank" class="btn btn-success btn-rounded btn-fw"
                    >Ver Detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>Juan Perez Rodiguez</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver Mapa</a
                  >
                </td>
                <td>2018-12-19 09:26:03 AM</td>
                <td>
                  Se encuentra en una calle transitada por lo que representa un
                  gran peligro para los automovies
                </td>
                <td>
                  <a href="{% url 'web:detalle-bache' %}" target="_blank" class="btn btn-success btn-rounded btn-fw"
                    >Ver Detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>Juan Perez Rodiguez</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver Mapa</a
                  >
                </td>
                <td>2018-12-19 09:26:03 AM</td>
                <td>
                  Se encuentra en una calle transitada por lo que representa un
                  gran peligro para los automovies
                </td>
                <td>
                  <a href="{% url 'web:detalle-bache' %}" target="_blank" class="btn btn-success btn-rounded btn-fw"
                    >Ver Detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>Juan Perez Rodiguez</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver Mapa</a
                  >
                </td>
                <td>2018-12-19 09:26:03 AM</td>
                <td>
                  Se encuentra en una calle transitada por lo que representa un
                  gran peligro para los automovies
                </td>
                <td>
                  <a href="{% url 'web:detalle-bache' %}" target="_blank" class="btn btn-success btn-rounded btn-fw"
                    >Ver Detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>Juan Perez Rodiguez</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver Mapa</a
                  >
                </td>
                <td>2018-12-19 09:26:03 AM</td>
                <td>
                  Se encuentra en una calle transitada por lo que representa un
                  gran peligro para los automovies
                </td>
                <td>
                  <a href="{% url 'web:detalle-bache' %}" target="_blank" class="btn btn-success btn-rounded btn-fw"
                    >Ver Detalle</a
                  >
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

web/templates/detalle_bache.html
{% extends 'global/base.html' %} {% load static %} {% block title %} Detalle del
bache {% endblock %} {% block style %}
<style></style>
{% endblock %} {% block content %}

<h1>VER DETALLE DEL BACHE</h1>

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Departamento</label>
              <div class="col-sm-9">
                <h1>Quetzaltenango</h1>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Municipio</label>
              <h1>Salcaja</h1>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nivel de daño</label>
              <div class="col-sm-9">
                <h1>Regular</h1>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label"
                >Coordenadas coordenadas</label
              >
              <div class="col-sm-9">
                <a
                  target="_blank"
                  href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                >
                  https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <img src="{% static 'global/images/bachesedited.jpg' %}" alt="" />
        </div>
        <a href="/" class="btn btn-success m-2">Regresar</a>
      </form>
    </div>
  </div>
</div>

{% endblock %} {% block js %}
<script></script>
{% endblock %}

web/templates/global/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{% static 'global/mdi/css/materialdesignicons.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'global/css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'global/css/addons.css' %}" />
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'global/css/my_styles.css' %}" />

    {% block style %} {% endblock %}
  </head>

  <body>
    <div class="container-scroller">
      <!-- partial:partials/_horizontal-navbar.html -->
      {% include 'global/components/horizontal_menu.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
          <div class="content-wrapper">
            {% block content %} {% endblock %}
            <!-- partial:partials/_footer.html -->
            {% include 'global/components/footer.html' %}
            <!-- partial -->
          </div>
          <!-- content-wrapper ends -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    {% include 'global/components/modal.html' %}
    <script src="{% static 'global/js/base.js' %}"></script>
    <script src="{% static 'global/js/addons.js' %}"></script>
    <script src="{% static 'global/plugins/js/axios.min.js' %}"></script>
    <script src="{% static 'global/js/http.js' %}"></script>
    <script src="{% static 'global/js/helpers.js' %}"></script>
    <script src="{% static 'global/js/scripts.js' %}"></script>

    <script src="{% static 'global/plugins/js/off-canvas.js' %} "></script>
    <script src="{% static 'global/plugins/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'global/plugins/js/template.js' %}"></script>
    <script src="{% static 'global/plugins/js/settings.js' %}"></script>
    <script src="{% static 'global/plugins/js/formpickers.js' %}"></script>
    <script src="{% static 'global/plugins/js/toastDemo.js' %}"></script>
    <script src="{% static 'global/plugins/js/alerts.js' %}"></script>
    <script src="{% static 'global/plugins/js/tooltips.js' %}"></script>
    <script src="{% static 'global/plugins/js/popover.js' %}"></script>
    <script src="{% static 'global/plugins/js/chart.js' %}"></script>
    <script src="{% static 'global/plugins/js/select2.js' %}"></script>
    <script>
      const modalTitle = document.getElementById("modal-title");
      const modalBody = document.getElementById("modal-body");
      const modalFooter = document.getElementById("modal-footer");
    </script>
    <script>
      (function ($) {
        "use strict";
        $(".dropify").dropify();
      })(jQuery);
      const handleSubmit = () => {
        showAlert("success-message", {
          title: "Correcto!",
          text: "Tus datos han sido guardados correctamente!",
        });
        setTimeout(function () {
          location.href = "/";
        }, 2000);
      };
    </script>
    {% csrf_token %} {% block js %}{% endblock %}
  </body>
</html>

web/templates/global/components/footer.html
<footer class="footer">
  <div class="w-100 clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
      Copyright © 2020 <a href="#">Control de baches</a>. All rights reserved.
    </span>
  </div>
</footer>

web/templates/global/components/horizontal_menu.html
{% load static %}
<div class="horizontal-menu">
  <nav class="navbar top-navbar col-lg-12 col-12 p-0">
    <div class="container">
      <div class="navbar-menu-wrapper d-flex align-items-stretch justify-content-between">
    
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href=""><img src="../../../static/global/images/logoumg.png" width="30" height="30" class="rounded-circle align-top" alt="logo"/><code>CONTROL DE BACHES</code></a>
          <a class="navbar-brand brand-logo-mini" href=""><img src="../../../static/global/images/logoumg.png" style="max-width: 56%;" class="rounded-circle align-top" alt="logo"/></a>
        </div>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="../../../static/global/images/profilepic.jpg" />
              <span class="nav-profile-name">{{user.username}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'web:logout' %}">
                <i class="mdi mdi-logout text-primary"></i>
                Cerrar Sesión
              </a>
            </div>
          </li>
          <li class="nav-item nav-toggler-item-right d-lg-none">
            <button class="navbar-toggler align-self-center" type="button" data-toggle="horizontal-menu-toggle">
              <span class="mdi mdi-menu"></span>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <nav class="bottom-navbar">
    <div class="container">
      <ul class="nav page-navigation">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:dashboard' %}">
            <i class="mdi mdi-view-dashboard-outline menu-icon"></i>
            <span class="menu-title">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:crear-bache' %}">
            <i class="mdi mdi-comment-plus menu-icon"></i>
            <span class="menu-title">Reportar Bache</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:reporte-baches' %}">
            <i class="mdi mdi-chart-bar menu-icon"></i>
            <span class="menu-title">Ver reporte de baches</span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>

web/templates/global/components/modal.html
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body">
        <h1>Loading...</h1>
      </div>
      <div class="modal-footer p-1" id="modal-footer">
      </div>
    </div>
  </div>
</div>

web/templates/reporte_baches.html
{% extends 'global/base.html' %} {% load static %} {% block title %} Reporte de
baches {% endblock %} {% block style %}
<style></style>
{% endblock %} {% block content %}

<h4>REPORTE GENERAL DE BACHES</h4>

<div class="row">
  <div class="card">
    <div class="card-body">
      <div class="col-12">
        <div class="table-responsive">
          <table id="order-listing" class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Departamento</th>
                <th>Municipio</th>
                <th>Nivel de daño</th>
                <th>Coordenadas</th>
                <th>Usuario que reporta</th>
                <th>Estado</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>Guatemala</td>
                <td>Mixco</td>
                <td>Medio</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver mapa</a
                  >
                </td>
                <td>Victor Maldonado</td>
                <td>
                  <label class="badge badge-info"
                    >En proceso de reparación</label
                  >
                </td>
                <td>
                  <a
                    href="{% url 'web:detalle-bache' %}"
                    target="_blank"
                    class="btn btn-outline-primary"
                    >Ver detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>2</td>
                <td>Solola</td>
                <td>Panajachel</td>
                <td>Severo</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver mapa</a
                  >
                </td>
                <td>Brayan Caceres</td>
                <td>
                  <label class="badge badge-danger">Pendiente</label>
                </td>
                <td>
                  <a
                    href="{% url 'web:detalle-bache' %}"
                    target="_blank"
                    class="btn btn-outline-primary"
                    >Ver detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>3</td>
                <td>Quiche</td>
                <td>Chichicastenango</td>
                <td>Severo</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver mapa</a
                  >
                </td>
                <td>Maria Gomez</td>
                <td>
                  <label class="badge badge-danger">Pendiente</label>
                </td>
                <td>
                  <a
                    href="{% url 'web:detalle-bache' %}"
                    target="_blank"
                    class="btn btn-outline-primary"
                    >Ver detalle</a
                  >
                </td>
              </tr>
              <tr>
                <td>4</td>
                <td>Totonicapan</td>
                <td>San Francisco El Alto</td>
                <td>Regular</td>
                <td>
                  <a
                    target="_blank"
                    href="https://www.google.com/maps/place/14%C2%B051'28.5%22N+91%C2%B030'43.0%22W/@14.85707,-91.510996,16.5z/data=!4m6!3m5!1s0x0:0x0!7e2!8m2!3d14.8579206!4d-91.5119367"
                    >Ver mapa</a
                  >
                </td>
                <td>Valeria Villa</td>
                <td>
                  <label class="badge badge-success">Reparado</label>
                </td>
                <td>
                  <a
                    href="{% url 'web:detalle-bache' %}"
                    target="_blank"
                    class="btn btn-outline-primary"
                    >Ver detalle</a
                  >
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block js %}
<script>
  (function ($) {
    "use strict";
    $(function () {
      $("#order-listing").DataTable({
        aLengthMenu: [
          [5, 10, 15, -1],
          [5, 10, 15, "All"],
        ],
        iDisplayLength: 10,
        language: {
          search: "",
        },
      });
      $("#order-listing").each(function () {
        var datatable = $(this);
        // SEARCH - Add the placeholder for Search and Turn this into in-line form control
        var search_input = datatable
          .closest(".dataTables_wrapper")
          .find("div[id$=_filter] input");
        search_input.attr("placeholder", "Search");
        search_input.removeClass("form-control-sm");
        // LENGTH - Inline-Form control
        var length_sel = datatable
          .closest(".dataTables_wrapper")
          .find("div[id$=_length] select");
        length_sel.removeClass("form-control-sm");
      });
    });
  })(jQuery);
</script>
{% endblock %}